name: angrysearch # you probably want to 'snapcraft register <name>'
version: git
summary: ANGRYsearch, a fast search tool for Linux
description: |
  ANGRYsearch is a tool written in Python and designed to show search results 
  as you type. 

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
    angrysearch:
        command: bin/angrysearch

parts:

  angrysearch:
    source: https://github.com/DoTheEvo/ANGRYsearch
    source-type: git
    plugin: python

    build-packages:
      - python3-pyqt5
